export const FIND_ALL_PRODUCTS = 'FIND_ALL_PRODUCTS';
export const FIND_ITEM_BY_ID = 'FIND_ITEM_BY_ID';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
